FROM node:16.14.2-alpine3.15 as builder
WORKDIR /frontend

ENV VITE_BACKEND_RUST=https://backend-rust-uilxvk2k3a-uc.a.run.app
ENV VITE_BACKEND_NODE=https://proyecto1-343723.uc.r.appspot.com

COPY ./package.json /frontend

RUN npm install --silent

COPY . .

RUN npm run build

# Handle Nginx
FROM nginx
COPY --from=builder /frontend/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf