FROM rust:1.59 as build

RUN USER=root cargo new --bin backend-rust
WORKDIR /backend-rust

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
RUN cargo build --release
RUN rm src/*.rs

# copy your source tree
COPY ./src ./src

# build for release
RUN rm ./target/release/deps/*
RUN cargo build --release

# our final base
FROM rust:1.59-slim-buster

# copy the build artifact from the build stage
COPY --from=build /backend-rust/target/release/backend-rust .

# set the startup command to run your binary
CMD ["./backend-rust"]