apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq
rules:
- apiGroups: 
    - ""
  resources: 
    - endpoints
  verbs: 
    - get
    - list
    - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rabbitmq
  namespace: squidgame
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: squidgame
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq

  kubectl apply -n squidgame -f rabbit-statefulset.yml
  kubectl apply -n squidgame -f rabbit-rbac.yml
  kubectl apply -n squidgame -f rabbit-secret.yml
  kubectl apply -n squidgame -f rabbit-statefulset.yml
