FROM nginx:1.21.6-alpine
ENV REACT_APP_API http://35.209.225.6
ENV REACT_APP_SOCKETS https://proyecto1-343723.uc.r.appspot.com/
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./build/ /usr/share/nginx/html