FROM golang:1.18.0-alpine3.15
WORKDIR /go/src/myapp
COPY . .
RUN go get ./
ENV GO_CLIENT_PORT=5000
ENV SERVER_NODE_PATH=34.69.197.207:50051
EXPOSE 5000
CMD ["go","run","main.go"]

#docker build -t rocket1530/client .
#docker run -d -p 5000:5000 --name client -e SERVER_NODE_PATH=35.238.6.126:50051 rocket1530/client